spring:
  application:
    name:user-center-backend
# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password: 
# session 失效时间
  session:
    timeout: 86400
# MyBatis-Plus Config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# Port
server:
  port: 8080
  servlet:
    context-path: /api

